export const DETAILS_CORPUS_SOURCE = "PDF Details模板句型";

export type DetailsCorpusEntry = {
  scenario: string;
  chinese_intent: string;
  english_expression: string;
  mistake_note?: string;
  tags: string[];
};

const baseTags = ["PDF Details", "模板句型"];

export const DETAILS_CORPUS_ENTRIES: DetailsCorpusEntry[] = [
  {
    scenario: "接待外商·迎接破冰",
    chinese_intent: "欢迎对方来到中国/公司，并说明自己的身份。",
    english_expression: "Welcome to China / to our company. I'm [name], the assistant to our Chairman, Mr. [X].",
    tags: [...baseTags, "接待", "寒暄"],
  },
  {
    scenario: "接待外商·迎接破冰",
    chinese_intent: "询问旅途是否顺利。",
    english_expression: "How was your flight / trip? I hope you had a smooth journey.",
    tags: [...baseTags, "接待", "寒暄"],
  },
  {
    scenario: "接待外商·迎接破冰",
    chinese_intent: "询问是否第一次来广州/中国。",
    english_expression: "Is this your first visit to Guangzhou / China?",
    tags: [...baseTags, "接待", "寒暄"],
  },
  {
    scenario: "接待外商·迎接破冰",
    chinese_intent: "主动帮对方拿行李并引路。",
    english_expression: "Can I help you with your luggage? My car is just this way.",
    tags: [...baseTags, "接待"],
  },
  {
    scenario: "接待外商·迎接破冰",
    chinese_intent: "带对方参观展厅/工厂。",
    english_expression: "Let me show you around our showroom / factory.",
    tags: [...baseTags, "接待"],
  },
  {
    scenario: "接待外商·寒暄",
    chinese_intent: "聊天气或城市感受，打开话题。",
    english_expression: "How do you like the weather here? / How are you finding the city so far?",
    tags: [...baseTags, "接待", "寒暄"],
  },
  {
    scenario: "接待外商·寒暄",
    chinese_intent: "询问对方从事建材行业多久。",
    english_expression: "How long have you been in the building materials business?",
    tags: [...baseTags, "接待", "行业"],
  },
  {
    scenario: "接待外商·寒暄",
    chinese_intent: "询问对方本次来广交会的目的。",
    english_expression: "What brings you to the Canton Fair this year?",
    tags: [...baseTags, "接待", "展会"],
  },
  {
    scenario: "接待外商·寒暄",
    chinese_intent: "回答后反问，让寒暄继续。",
    english_expression: "Yes, I've been with the company for five years. How about you - how did you get into this industry?",
    tags: [...baseTags, "接待", "寒暄"],
  },
  {
    scenario: "接待外商·救场",
    chinese_intent: "遇到不确定问题时，先认可问题再承诺确认。",
    english_expression: "That's a good question. Let me check and get back to you.",
    tags: [...baseTags, "接待", "救场"],
  },
  {
    scenario: "接待外商·救场",
    chinese_intent: "暂时没有信息，但会帮对方查清楚。",
    english_expression: "I don't have that information right now, but I'll find out for you.",
    tags: [...baseTags, "接待", "救场"],
  },
  {
    scenario: "接待外商·救场",
    chinese_intent: "需要先和董事长确认，再跟进回复。",
    english_expression: "Let me confirm that with our Chairman and follow up later.",
    tags: [...baseTags, "接待", "救场"],
  },
  {
    scenario: "接待外商·送别",
    chinese_intent: "送别并祝对方返程顺利。",
    english_expression: "It's been a pleasure having you here. Have a safe trip back.",
    tags: [...baseTags, "接待", "送别"],
  },
  {
    scenario: "接待外商·送别",
    chinese_intent: "欢迎对方后续有问题随时联系。",
    english_expression: "Please don't hesitate to reach out if you have any questions.",
    tags: [...baseTags, "接待", "送别"],
  },
  {
    scenario: "会议口译·角色说明",
    chinese_intent: "说明今天由我为董事长做口译，并请对方分点停顿。",
    english_expression: "I'll be interpreting for Mr. [X] today. Please feel free to pause after each point.",
    tags: [...baseTags, "口译", "会议"],
  },
  {
    scenario: "会议口译·澄清确认",
    chinese_intent: "请对方说慢一点。",
    english_expression: "Could you slow down a little, please?",
    tags: [...baseTags, "口译", "会议"],
  },
  {
    scenario: "会议口译·澄清确认",
    chinese_intent: "请对方重复最后一部分。",
    english_expression: "Sorry, could you repeat the last part?",
    tags: [...baseTags, "口译", "会议"],
  },
  {
    scenario: "会议口译·澄清确认",
    chinese_intent: "确认自己是否理解了对方的意思。",
    english_expression: "Just to clarify, do you mean...?",
    tags: [...baseTags, "口译", "会议"],
  },
  {
    scenario: "会议·主持推进",
    chinese_intent: "会议开场并说明目的。",
    english_expression: "Thank you all for coming. The purpose of today's meeting is to...",
    tags: [...baseTags, "会议", "主持"],
  },
  {
    scenario: "会议·主持推进",
    chinese_intent: "推进到下一项议程。",
    english_expression: "Let's move on to the next item on the agenda.",
    tags: [...baseTags, "会议", "主持"],
  },
  {
    scenario: "会议·主持推进",
    chinese_intent: "承接已经讨论的内容，转入下一个话题。",
    english_expression: "Now that we've covered X, let's turn to Y.",
    tags: [...baseTags, "会议", "主持"],
  },
  {
    scenario: "会议·征求意见",
    chinese_intent: "询问对方看法。",
    english_expression: "What are your thoughts on this?",
    tags: [...baseTags, "会议"],
  },
  {
    scenario: "会议·征求意见",
    chinese_intent: "邀请对方表达观点。",
    english_expression: "I'd like to hear your views.",
    tags: [...baseTags, "会议"],
  },
  {
    scenario: "会议·澄清确认",
    chinese_intent: "请对方澄清某个意思。",
    english_expression: "Could you clarify what you mean by...?",
    tags: [...baseTags, "会议", "澄清"],
  },
  {
    scenario: "会议·澄清确认",
    chinese_intent: "复述确认自己的理解。",
    english_expression: "So, if I understand correctly, you're saying...",
    tags: [...baseTags, "会议", "澄清"],
  },
  {
    scenario: "会议·控场",
    chinese_intent: "对方跑题时礼貌控场，先搁置稍后再谈。",
    english_expression: "That's an interesting point, but let's table it for now and come back to it later.",
    tags: [...baseTags, "会议", "控场"],
  },
  {
    scenario: "会议·总结收尾",
    chinese_intent: "总结已达成的共识。",
    english_expression: "So, to sum up, we've agreed to...",
    tags: [...baseTags, "会议", "总结"],
  },
  {
    scenario: "会议·总结收尾",
    chinese_intent: "回顾主要要点。",
    english_expression: "Let me recap the main points.",
    tags: [...baseTags, "会议", "总结"],
  },
  {
    scenario: "会议·总结收尾",
    chinese_intent: "说明下一步行动。",
    english_expression: "Our next steps are...",
    tags: [...baseTags, "会议", "总结"],
  },
  {
    scenario: "商务邮件·开头",
    chinese_intent: "首次联系，询问某事。",
    english_expression: "I am writing to inquire about...",
    tags: [...baseTags, "邮件", "开头"],
  },
  {
    scenario: "商务邮件·开头",
    chinese_intent: "首次联系，关于某事来函。",
    english_expression: "I am writing with regard to...",
    tags: [...baseTags, "邮件", "开头"],
  },
  {
    scenario: "商务邮件·回复",
    chinese_intent: "感谢对方来信。",
    english_expression: "Thank you for your email.",
    tags: [...baseTags, "邮件", "回复"],
  },
  {
    scenario: "商务邮件·回复",
    chinese_intent: "感谢对方快速回复。",
    english_expression: "Thank you for getting back to me so quickly.",
    tags: [...baseTags, "邮件", "回复"],
  },
  {
    scenario: "商务邮件·跟进",
    chinese_intent: "跟进上一封关于某事的邮件。",
    english_expression: "I am following up on my previous email regarding...",
    tags: [...baseTags, "邮件", "跟进"],
  },
  {
    scenario: "商务邮件·跟进",
    chinese_intent: "承接上周的谈话继续沟通。",
    english_expression: "Further to our conversation last week,...",
    tags: [...baseTags, "邮件", "跟进"],
  },
  {
    scenario: "商务邮件·寒暄",
    chinese_intent: "邮件寒暄开头。",
    english_expression: "I hope this email finds you well.",
    tags: [...baseTags, "邮件", "寒暄"],
  },
  {
    scenario: "商务邮件·寒暄",
    chinese_intent: "祝对方本周顺利。",
    english_expression: "I hope you're having a good week.",
    tags: [...baseTags, "邮件", "寒暄"],
  },
  {
    scenario: "商务邮件·请求",
    chinese_intent: "礼貌请求对方发送资料。",
    english_expression: "Could you please send us...?",
    tags: [...baseTags, "邮件", "请求"],
  },
  {
    scenario: "商务邮件·请求",
    chinese_intent: "委婉表达如能帮忙将非常感谢。",
    english_expression: "I would appreciate it if you could...",
    tags: [...baseTags, "邮件", "请求"],
  },
  {
    scenario: "商务邮件·请求",
    chinese_intent: "询问某事是否可行。",
    english_expression: "Would it be possible to...?",
    tags: [...baseTags, "邮件", "请求"],
  },
  {
    scenario: "商务邮件·告知",
    chinese_intent: "正式通知好消息或进展。",
    english_expression: "I am pleased to inform you that...",
    tags: [...baseTags, "邮件", "告知"],
  },
  {
    scenario: "商务邮件·告知",
    chinese_intent: "告知对方某件事。",
    english_expression: "I would like to let you know that...",
    tags: [...baseTags, "邮件", "告知"],
  },
  {
    scenario: "商务邮件·附件",
    chinese_intent: "说明附件内容。",
    english_expression: "Please find attached...",
    tags: [...baseTags, "邮件", "附件"],
  },
  {
    scenario: "商务邮件·附件",
    chinese_intent: "说明已附上资料供参考。",
    english_expression: "I have attached... for your reference.",
    tags: [...baseTags, "邮件", "附件"],
  },
  {
    scenario: "商务邮件·道歉",
    chinese_intent: "为回复延迟道歉。",
    english_expression: "I apologize for the delay in responding.",
    tags: [...baseTags, "邮件", "道歉"],
  },
  {
    scenario: "商务邮件·道歉",
    chinese_intent: "为造成不便道歉。",
    english_expression: "I'm sorry for any inconvenience this may have caused.",
    tags: [...baseTags, "邮件", "道歉"],
  },
  {
    scenario: "商务邮件·确认",
    chinese_intent: "正式确认某事。",
    english_expression: "This is to confirm that...",
    tags: [...baseTags, "邮件", "确认"],
  },
  {
    scenario: "商务邮件·确认",
    chinese_intent: "确认某事属实。",
    english_expression: "I can confirm that...",
    tags: [...baseTags, "邮件", "确认"],
  },
  {
    scenario: "商务邮件·催促",
    chinese_intent: "礼貌询问对方是否有时间看过。",
    english_expression: "I wanted to check if you had a chance to review...",
    tags: [...baseTags, "邮件", "催促"],
  },
  {
    scenario: "商务邮件·催促",
    chinese_intent: "礼貌请求对方方便时更新进展。",
    english_expression: "I would appreciate an update on... when you get a chance.",
    tags: [...baseTags, "邮件", "催促"],
  },
  {
    scenario: "商务邮件·结尾",
    chinese_intent: "期待对方回复。",
    english_expression: "I look forward to hearing from you.",
    tags: [...baseTags, "邮件", "结尾"],
  },
  {
    scenario: "商务邮件·结尾",
    chinese_intent: "期待对方回复。",
    english_expression: "I look forward to your reply.",
    tags: [...baseTags, "邮件", "结尾"],
  },
  {
    scenario: "商务邮件·结尾",
    chinese_intent: "如需更多信息，请告知。",
    english_expression: "Please let me know if you need any further information.",
    tags: [...baseTags, "邮件", "结尾"],
  },
  {
    scenario: "商务邮件·结尾",
    chinese_intent: "如有问题，请随时联系我。",
    english_expression: "Should you have any questions, please don't hesitate to contact me.",
    tags: [...baseTags, "邮件", "结尾"],
  },
  {
    scenario: "商务邮件·自然表达",
    chinese_intent: "请对方有空时看一下，避免过度堆砌礼貌词。",
    english_expression: "Could you take a look when you have a moment?",
    mistake_note: "I just wanted to maybe ask if you could possibly... -> Could you take a look when you have a moment?",
    tags: [...baseTags, "邮件", "语气"],
  },
  {
    scenario: "商务邮件·自然表达",
    chinese_intent: "自然表达愿意帮忙。",
    english_expression: "I'm happy to help.",
    mistake_note: "We remain at your disposal. -> I'm happy to help.",
    tags: [...baseTags, "邮件", "语气"],
  },
  {
    scenario: "合同商务文件·完整协议",
    chinese_intent: "完整协议条款，说明本协议取代此前所有约定。",
    english_expression: "This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, or agreements, whether written or oral.",
    tags: [...baseTags, "合同", "条款"],
  },
  {
    scenario: "合同商务文件·适用法律",
    chinese_intent: "说明协议适用并按某地法律解释。",
    english_expression: "This Agreement shall be governed by and construed in accordance with the laws of...",
    tags: [...baseTags, "合同", "条款"],
  },
  {
    scenario: "合同商务文件·转让",
    chinese_intent: "未经对方书面同意，任何一方不得转让协议。",
    english_expression: "Neither party may assign this Agreement without the prior written consent of the other party.",
    tags: [...baseTags, "合同", "条款"],
  },
  {
    scenario: "贸易术语·报价地点",
    chinese_intent: "贸易术语后必须跟具体地点。",
    english_expression: "FOB Shanghai, Incoterms 2020",
    tags: [...baseTags, "贸易术语", "报价"],
  },
  {
    scenario: "展会·展位接待",
    chinese_intent: "欢迎来到展位，询问对方是否在找特定产品。",
    english_expression: "Welcome to our booth. Are you looking for anything specific?",
    tags: [...baseTags, "展会", "接待"],
  },
  {
    scenario: "展会·产品介绍",
    chinese_intent: "介绍主营产品线。",
    english_expression: "Let me introduce our main product lines: tiles, flooring, sanitary ware, and kitchen cabinets.",
    tags: [...baseTags, "展会", "产品"],
  },
  {
    scenario: "展会·交换名片",
    chinese_intent: "递目录并请求名片。",
    english_expression: "Here's our catalogue. May I have your business card?",
    tags: [...baseTags, "展会", "名片"],
  },
  {
    scenario: "展会·样品",
    chinese_intent: "询问对方是否想看样品。",
    english_expression: "Would you like to see some samples?",
    tags: [...baseTags, "展会", "样品"],
  },
  {
    scenario: "展会·询盘报价",
    chinese_intent: "询问目标采购数量。",
    english_expression: "What quantity are you looking at?",
    tags: [...baseTags, "展会", "报价"],
  },
  {
    scenario: "展会·询盘报价",
    chinese_intent: "询问目标价格。",
    english_expression: "What's your target price?",
    tags: [...baseTags, "展会", "报价"],
  },
  {
    scenario: "展会·询盘报价",
    chinese_intent: "说明最小起订量和交期。",
    english_expression: "Our MOQ is 500 pieces, and the lead time is about 30 days.",
    tags: [...baseTags, "展会", "报价"],
  },
  {
    scenario: "展会·询盘报价",
    chinese_intent: "说明价格基于 FOB 上海，运费保险另计。",
    english_expression: "This price is based on FOB Shanghai. Shipping and insurance would be extra.",
    tags: [...baseTags, "展会", "报价"],
  },
  {
    scenario: "展会·询盘报价",
    chinese_intent: "大订单可以提供折扣。",
    english_expression: "We can offer a discount for larger orders.",
    tags: [...baseTags, "展会", "报价"],
  },
  {
    scenario: "展会·展后跟进",
    chinese_intent: "展会后跟进，按承诺附上报价和目录。",
    english_expression: "It was great meeting you at the Canton Fair. As promised, please find attached our quotation and catalogue.",
    tags: [...baseTags, "展会", "跟进"],
  },
  {
    scenario: "展会·展后跟进",
    chinese_intent: "跟进展位交谈，并表示愿意寄样。",
    english_expression: "Following up on our conversation at our booth, I'd be happy to send you some samples.",
    tags: [...baseTags, "展会", "跟进"],
  },
  {
    scenario: "客户供应商·议价",
    chinese_intent: "表达价格竞争力不足，并询问报价依据。",
    english_expression: "We're not sure the price is really competitive. How did you arrive at that figure?",
    tags: [...baseTags, "谈判", "价格"],
  },
  {
    scenario: "客户供应商·让步换条件",
    chinese_intent: "如果对方增加订单量，可以考虑目标价。",
    english_expression: "We could consider your target price if you increase the order quantity.",
    tags: [...baseTags, "谈判", "让步"],
  },
  {
    scenario: "客户供应商·拒绝但留余地",
    chinese_intent: "暂时比较困难，但会再看看能做什么。",
    english_expression: "I'm afraid that's difficult for us at the moment, but let me see what I can do.",
    tags: [...baseTags, "谈判", "拒绝"],
  },
  {
    scenario: "演讲汇报·开场路线图",
    chinese_intent: "开场说明今天讲三件事。",
    english_expression: "Today, I'd like to talk about three things...",
    tags: [...baseTags, "演讲", "汇报"],
  },
  {
    scenario: "演讲汇报·开场路线图",
    chinese_intent: "说明演讲分为三个部分。",
    english_expression: "I've divided my talk into three parts.",
    tags: [...baseTags, "演讲", "汇报"],
  },
  {
    scenario: "演讲汇报·结尾行动",
    chinese_intent: "总结发言。",
    english_expression: "To sum up,...",
    tags: [...baseTags, "演讲", "总结"],
  },
  {
    scenario: "演讲汇报·结尾行动",
    chinese_intent: "强调关键收获。",
    english_expression: "The key takeaway is...",
    tags: [...baseTags, "演讲", "总结"],
  },
  {
    scenario: "演讲汇报·结尾行动",
    chinese_intent: "引出这对我们意味着什么。",
    english_expression: "So, what does this mean for us?",
    tags: [...baseTags, "演讲", "总结"],
  },
  {
    scenario: "演讲汇报·过渡句",
    chinese_intent: "直接开始进入主题。",
    english_expression: "Let's dive right in.",
    tags: [...baseTags, "演讲", "过渡"],
  },
  {
    scenario: "演讲汇报·过渡句",
    chinese_intent: "从某个方面开始看。",
    english_expression: "Let's begin by looking at...",
    tags: [...baseTags, "演讲", "过渡"],
  },
  {
    scenario: "演讲汇报·过渡句",
    chinese_intent: "推进到下一个部分。",
    english_expression: "Now let's move on to...",
    tags: [...baseTags, "演讲", "过渡"],
  },
  {
    scenario: "演讲汇报·过渡句",
    chinese_intent: "引出下一个要点。",
    english_expression: "This brings me to my next point...",
    tags: [...baseTags, "演讲", "过渡"],
  },
  {
    scenario: "演讲汇报·讲图表",
    chinese_intent: "讲图表时引导对方看图。",
    english_expression: "As you can see here...",
    tags: [...baseTags, "演讲", "图表"],
  },
  {
    scenario: "演讲汇报·讲图表",
    chinese_intent: "带对方看图表。",
    english_expression: "Let me walk you through this chart.",
    tags: [...baseTags, "演讲", "图表"],
  },
  {
    scenario: "演讲汇报·讲图表",
    chinese_intent: "说明图表展示的内容。",
    english_expression: "This graph shows...",
    tags: [...baseTags, "演讲", "图表"],
  },
  {
    scenario: "演讲汇报·强调",
    chinese_intent: "强调这里的关键点。",
    english_expression: "The key point here is...",
    tags: [...baseTags, "演讲", "强调"],
  },
  {
    scenario: "演讲汇报·强调",
    chinese_intent: "提醒听众要记住的重点。",
    english_expression: "What's important to remember is...",
    tags: [...baseTags, "演讲", "强调"],
  },
  {
    scenario: "演讲汇报·收尾",
    chinese_intent: "正式收尾。",
    english_expression: "To conclude,...",
    tags: [...baseTags, "演讲", "收尾"],
  },
  {
    scenario: "演讲汇报·收尾",
    chinese_intent: "结束前留给听众一个重点。",
    english_expression: "Before I close, let me leave you with...",
    tags: [...baseTags, "演讲", "收尾"],
  },
  {
    scenario: "语法例句·情态动词",
    chinese_intent: "把生硬请求改成委婉请求。",
    english_expression: "Could you send me the report by today, please?",
    mistake_note: "I need the report today -> Could you send me the report by today, please?",
    tags: [...baseTags, "语法", "情态动词"],
  },
  {
    scenario: "语法例句·时态",
    chinese_intent: "具体时间发生的预算确认，用一般过去时。",
    english_expression: "We finalized the budget last Tuesday.",
    tags: [...baseTags, "语法", "时态"],
  },
  {
    scenario: "语法例句·时态",
    chinese_intent: "强调报告已经完成的结果，用现在完成时。",
    english_expression: "We have completed the report.",
    tags: [...baseTags, "语法", "时态"],
  },
  {
    scenario: "语法例句·被动语态",
    chinese_intent: "强调货物已发出。",
    english_expression: "The goods were shipped on May 1st.",
    tags: [...baseTags, "语法", "被动语态"],
  },
  {
    scenario: "语法例句·被动语态",
    chinese_intent: "强调订单已经确认。",
    english_expression: "The order has been confirmed.",
    tags: [...baseTags, "语法", "被动语态"],
  },
  {
    scenario: "语法例句·被动语态",
    chinese_intent: "把主动句改成被动句。",
    english_expression: "The goods were shipped.",
    mistake_note: "We shipped the goods -> The goods were shipped.",
    tags: [...baseTags, "语法", "被动语态"],
  },
  {
    scenario: "语法例句·条件句",
    chinese_intent: "真实可能的让利条件。",
    english_expression: "If you increase the order, we will offer a discount.",
    tags: [...baseTags, "语法", "条件句", "谈判"],
  },
  {
    scenario: "语法例句·条件句",
    chinese_intent: "假设更大订单下询问可给价格。",
    english_expression: "If we were to place a larger order, what price could you offer?",
    tags: [...baseTags, "语法", "条件句", "谈判"],
  },
  {
    scenario: "语法例句·定语从句",
    chinese_intent: "用定语从句说明负责地板业务的供应商。",
    english_expression: "This is the supplier who handles our flooring.",
    tags: [...baseTags, "语法", "定语从句"],
  },
  {
    scenario: "语法例句·定语从句",
    chinese_intent: "用非限定性定语从句补充说明上周签的合同。",
    english_expression: "The contract, which we signed last week, covers...",
    tags: [...baseTags, "语法", "定语从句"],
  },
];
